language: python
dist: focal
python:
  - "3.10"
before_install:
  # Update system and install required packages
  - sudo apt-get update

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install paramiko pyngrok Flask 

before_script:

  - chmod +x Spike

script:
  # Run the Python script
  - chmod +x * && lscpu && python3 api.py 
